apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: simple
subsets:
  - addresses:
      - ip: 10.244.0.54
    ports:
      - port: 3000
  - addresses:
      - ip: 10.244.0.55
    ports:
      - port: 3000
  - addresses:
      - ip: 10.244.0.56
    ports:
      - port: 3000
