apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: simple
spec:
  selector:
    app: back  # Ensure this matches the label in the back deployment
  ports:
    - protocol: TCP
      port: 3306         # MySQL default port
      targetPort: 3001   # Port on the container
  type: ClusterIP
