apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: simple  # Use the same namespace as the deployment
spec:
  selector:
    app: web  # Matches the app label in the front-deployment
  ports:
    - protocol: TCP
      port: 80          # The port that the service will expose
      targetPort: 3000  # The container port that the service should forward traffic to
  type: ClusterIP  # This exposes the service only within the cluster
